apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: omni
resources:
  - migration.yaml
  - voice-canary.yaml
images:
  - name: omni-api
    newTag: candidate
  - name: omni-voice
    newTag: candidate
